#!/bin/bash

artist="$1"
song="$2"

artist=$(echo "$artist" | tr '[:upper:]' '[:lower:]' )
artist="$(tr '[:lower:]' '[:upper:]' <<< "${artist:0:1}")${artist:1}" # capitalize artist
artist_with_dash=${artist// /-}
song_with_dash=$(echo "$song" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
link="https://genius.com/$artist_with_dash-$song_with_dash-lyrics"

    while [ -z "$output" ]
do
    output=$(curl -s "$link" | sed -n  '/<div class="song_body-lyrics">/,/<\/div>/p' | sed -E 's/>([[a-zA-Z])/>\n\1/g' | sed -E 's/.<a/<a/g' | sed '/<a/,/>/d' | sed 's/<br>//g' | sed 's/<.*>//g')
    output=$(echo "$output" | awk '!NF {if (++n <= 2) print; next}; {n=0;print}') #remove double+ new lines
done

echo "$output" | less
