#!/bin/bash
xrandr --output HDMI-1 --auto
xrandr --output HDMI-1 --left-of eDP-1
feh --bg-fill $CURRENT_WALL
picom -b --backend glx --experimental-backends & disown
setxkbmap -layout pt -option caps:escape &
xmodmap -e "clear lock"
xmodmap -e "keycode 9 = Caps_Lock NoSymbol Caps_Lock"
xmodmap -e "keycode 66 = Escape NoSymbol Escape"
i3-msg "restart"
