#!/bin/bash
#xrandr --output HDMI-1 --off
xrandr --output HDMI-1 --auto
xrandr --output HDMI-1 --left-of eDP-1
feh --bg-fill ~/Pictures/Wallpapers/blue-horizon.jpg
picom -b --backend glx --experimental-backends & disown

