#!/bin/bash

cd "$DOTFILES" || exit
new_files=$(git status -s | grep '??' | grep 'scripts' | cut -d '/' -f 2)

[ -z "$new_files" ] && exit

for script in $new_files
do
        read -r -p "Please enter description for script $script "
        line="- [$script](./scripts/$script) - $REPLY"
        echo "$line" >> "$DOTFILES/README.md"
done
