#!/bin/bash

[[ "$PWD" == *dotfiles* ||"$PWD" == *scripts* ]] || exit
cd "$DOTFILES" || exit

new_files=$(git status -s | grep '??' | grep 'scripts' | cut -d '/' -f 2)

[ -z "$new_files" ] && exit

for script in $new_files
do
        read -r -p "Please enter description for script $script "

        if [ -n "$REPLY" ]
        then
             line="- [$script](./scripts/$script) - $REPLY"
             echo "$line" >> "$DOTFILES/README.md"
        fi
done
/usr/bin/git add README.md
