#!/bin/bash

extension=$(dmenu -p "Enter extension")
extension=${extension:="cenas"}
mkdir -p /tmp/vim-anywhere
file=$(mktemp "/tmp/vim-anywhere/cenasXXXXXX.$extension")
"$TERMINAL" -e nvim "$file"
[ "$(cat "$file")" ] && xclip -selection c < "$file"
