#!/bin/bash

i3dir=$DOTFILES/i3/config
walldir=$HOME/Pictures/Wallpapers

randwall() {
    length=`ls $walldir | wc -l`
    number=$((($RANDOM%$length)+1))
    name=`ls $walldir | head -$number | tail -1`
    echo $name
}

if [[ $# -eq 1 ]]; then
    file=$1
else
    file="$walldir/$(randwall)"
fi

feh --bg-fill "$file" --no-fehbg
ln -sf "$file" "$DOTFILES/current_wallpaper"
#sed -i "s|feh.*|feh --bg-fill $file|" $i3dir
