#!/bin/bash

randwall() {
    length=$(find "$WALLPAPERS" -maxdepth 1 -type f -print | wc -l)
    number=$(((RANDOM%length)+1))
    name=$(find "$WALLPAPERS" -maxdepth 1 -type f -print |
        head -"$number" | tail -1 | awk -F '/' '{printf $NF}')
    echo "$name"
}

try() {
    curl "$(xclip -o -selection c)" | feh - --bg-fill ; i3-msg "workspace 7"
    exit
}

save() {
    name=$(echo | dmenu -p "Wallname : ")
    curl "$(xclip -o -selection c)" > "wall"
    filetype=$(file wall | cut -d ':' -f2 | cut -d ' ' -f2)
    mv "wall" "$WALLPAPERS/$name.${filetype,,}"
}

delete(){
    rm "$(readlink "$CURRENT_WALL")"
    wallpaper
}

if [[ "$1" == "prompt" ]]; then
    option=$(printf "try\nsave\ndelete" | dmenu -l 20)
    eval "$option"

elif [[ $# -eq 1 ]]; then
    file="$1"
else
    file="$WALLPAPERS/$(randwall)"
fi

feh --bg-fill "$file" --no-fehbg
ln -sf "$file" "$CURRENT_WALL"
changeMeWall.spell
