env:
  TERM: xterm-256color
  WINIT_X11_SCALE_FACTOR: "1.5"

# Window configurations
window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 0
    y: 0

  decorations: full

scrolling:
  multiplier: 1

# Font configurations
font:
  normal:
    family: Hack Nerd Font
    style: Regular

  bold:
    family: Hack Nerd Font
    style: Bold

  italic:
    family: Hack Nerd Font
    style: Italic

  size: 8.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  scale_with_dpi: true

  use_thin_strokes: false

draw_bold_text_with_bright_colors: true
# ...
schemes:
  ayu_dark: &ayu
    primary:
       background: '0x282a36'
       foreground: '0xf8f8f2'


      # Normal colors
    normal:
      black: '0x01060E'
      red: '0xEA6C73'
      green: '0x91B362'
      yellow: '0xF9AF4F'
      blue: '0x53BDFA'
      magenta: '0xA37ACC'
      cyan: '0x90E1C6'
      white: '0xC7C7C7'

    # Bright colors
    bright:
      black: '0x686868'
      red: '0xF07178'
      green: '0xC2D94C'
      yellow: '0xFFB454'
      blue: '0x59C2FF'
      magenta: '0xD4BFFF'
      cyan: '0x95E6CB'
      white: '0xFFFFFF'

  custom: &custom
    primary:
      background: '0x222222'
      foreground: '0xeaeaea'

    # Normal colors
    normal:
      black:   '0x1b1918'
      red:     '0xf22c40'
      green:   '0x5ab738'
      yellow:  '0xd5911a'
      blue:    '0x407ee7'
      magenta: '0x6666ea'
      cyan:    '0x70c0ba'
      white:   '0xeaeaea'

    # Bright colors
    bright:
      black:   '0x766e66'
      red:     '0xff3334'
      green:   '0x9ec400'
      yellow:  '0xe7c547'
      blue:    '0x7aa6da'
      magenta: '0xb77ee0'
      cyan:    '0x00ad9c'
      white:   '0xffffff'

  base16: &base16
      background: '0x222222'




    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '0x9a9a9a'
    #bright_foreground: '0xffffff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  cursor:
    text: '0x44475a'
    cursor: '0xf8f8f2'
  selection:
    background: '0x506070'
  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbfbfbf'

  # Bright colors
  bright:
    black:   '0x4d4d4d'
    red:     '0xff6e67'
    green:   '0x5af78e'
    yellow:  '0xf4f99d'
    blue:    '0xcaa9fa'
    magenta: '0xff92d0'
    cyan:    '0x9aedfe'
    white:   '0xe6e6e6'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  dim:
    black:   '0x14151b'
    red:     '0xff2222'
    green:   '0x1ef956'
    yellow:  '0xebf85b'
    blue:    '0x4d5b86'
    magenta: '0xff46b0'
    cyan:    '0x59dffc'
    white:   '0xe6e6d1'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '0xff00ff' }`
  #
  indexed_colors: []


# Visual bell
bell:
  animation: EaseOutExpo
  duration: 0

background_opacity: 0.5

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true
  background: '0x506070'

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  faux_scrolling_lines: 1
  hide_when_typing: false

cursor:
  style: Beam
  unfocused_hollow: false

window.dynamic_title: true

live_config_reload: true

shell:
  program: /bin/zsh
  args:
    - -c
    - echo && exec zsh

key_bindings:
  - { key: Return,   mods: Shift|Super, action: SpawnNewInstance }
